In [1]:
import pandas as pd

df = pd.read_excel("customer_shopping_behavior.xlsx")

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,C001,47,Female,T-Shirt,Clothing,121,Atlanta,9,Grey,Summer,3.8,Yes,Express,Yes,Yes,20,Cash,Frequent
1,C002,32,Male,Sneakers,Footwear,99,Denver,XL,Blue,Winter,4.2,Yes,Express,Yes,Yes,20,Debit Card,Occasionally
2,C003,20,Male,Boots,Footwear,111,Miami,9,Red,Summer,3.8,No,Store Pickup,No,Yes,15,Credit Card,Occasionally
3,C004,44,Male,Boots,Footwear,100,Chicago,9,Brown,Summer,4.8,No,Store Pickup,No,No,2,PayPal,Rarely
4,C005,23,Male,Watch,Accessories,167,New York,8,Black,Winter,4.4,No,Two-Day,Yes,Yes,13,Cash,Monthly

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             100 non-null    object
 1   Age                     100 non-null    int64
 2   Gender                  100 non-null    object
 3   Item Purchased          100 non-null    object
 4   Category                100 non-null    object
 5   Purchase Amount (USD)   100 non-null    int64
 6   Location                100 non-null    object
 7   Size                    100 non-null    object
 8   Color                   100 non-null    object
 9   Season                  100 non-null    object
 10  Review Rating           100 non-null    float64
 11  Subscription Status     100 non-null    object
 12  Shipping Type           100 non-null    object
 13  Discount Applied        100 non-null    object
 14  Promo Code Used         100 non-null    object
 15  Previous Purchases      100 non-null    int64
 16  Payment Method          100 non-null    object
 17  Frequency of Purchases  100 non-null    object
dtypes: float64(1), int64(3), object(14)
memory usage: 14.2+ KB

In [4]:
df.describe()

              Age  Purchase Amount (USD)  Review Rating  Previous Purchases
count  100.000000              100.00000     100.000000          100.000000
mean    38.760000              140.58000       4.022000           10.120000
std     12.879488               61.20477       0.585443            6.005519
min     18.000000               21.00000       3.000000            0.000000
25%     26.750000               97.00000       3.500000            5.000000
50%     38.500000              141.50000       4.000000           11.000000
75%     50.250000              192.25000       4.500000           14.250000
max     60.000000              250.00000       5.000000           20.000000

In [5]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,100,100.000000,100,100,100,100.00000,100,100,100,100,100.000000,100,100,100,100,100.000000,100,100
unique,100,NaN,2,11,3,NaN,10,9,10,4,NaN,2,4,2,2,NaN,4,4
top,C001,NaN,Male,Boots,Footwear,NaN,New York,XL,Red,Summer,NaN,No,Two-Day,No,Yes,NaN,Debit Card,Monthly
freq,1,NaN,53,17,42,NaN,19,16,15,35,NaN,56,33,52,58,NaN,28,30
mean,NaN,38.760000,NaN,NaN,NaN,140.58000,NaN,NaN,NaN,NaN,4.022000,NaN,NaN,NaN,NaN,10.120000,NaN,NaN
std,NaN,12.879488,NaN,NaN,NaN,61.20477,NaN,NaN,NaN,NaN,0.585443,NaN,NaN,NaN,NaN,6.005519,NaN,NaN
min,NaN,18.000000,NaN,NaN,NaN,21.00000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,NaN,26.750000,NaN,NaN,NaN,97.00000,NaN,NaN,NaN,NaN,3.500000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN
50%,NaN,38.500000,NaN,NaN,NaN,141.50000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,11.000000,NaN,NaN
75%,NaN,50.250000,NaN,NaN,NaN,192.25000,NaN,NaN,NaN,NaN,4.500000,NaN,NaN,NaN,NaN,14.250000,NaN,NaN
max,NaN,60.000000,NaN,NaN,NaN,250.00000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,20.000000,NaN,NaN

In [6]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [7]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [8]:
df.columns = df.columns.str.replace(' ','_')

In [9]:
df = df.rename(columns={'Purchase_Amount_(USD)':'Purchase_Amount'})

In [10]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category',
       'Purchase_Amount', 'Location', 'Size', 'Color', 'Season',
       'Review_Rating', 'Subscription_Status', 'Shipping_Type',
       'Discount_Applied', 'Promo_Code_Used', 'Previous_Purchases',
       'Payment_Method', 'Frequency_of_Purchases'],
      dtype='object')

In [11]:
# Create Age_Group
labels = ["Young", "Adult", "Middle-aged", "Senior"]

df["Age_Group"] = pd.qcut(df["Age"], q=4, labels=labels)

In [12]:
df[["Age", "Age_Group"]].head(10)

   Age    Age_Group
0   47  Middle-aged
1   32        Adult
2   20        Young
3   44  Middle-aged
4   23        Young
5   48  Middle-aged
6   50  Middle-aged
7   41  Middle-aged
8   18        Young
9   46  Middle-aged

In [13]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category',
       'Purchase_Amount', 'Location', 'Size', 'Color', 'Season',
       'Review_Rating', 'Subscription_Status', 'Shipping_Type',
       'Discount_Applied', 'Promo_Code_Used', 'Previous_Purchases',
       'Payment_Method', 'Frequency_of_Purchases', 'Age_Group'],
      dtype='object')

In [14]:
# create column Purchase_Frequency_Days
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90,
    'Frequent': 1,
    'Occasionally':120,
    'Rarely':180
    
}

# Map the Frequency_of_Purchases to days
df["Purchase_Frequency_Days"] = df["Frequency_of_Purchases"].map(frequency_mapping)

In [15]:
df[["Purchase_Frequency_Days", "Frequency_of_Purchases"]].head(10)

   Purchase_Frequency_Days Frequency_of_Purchases
0                        1               Frequent
1                      120           Occasionally
2                      120           Occasionally
3                      180                 Rarely
4                       30                Monthly
5                        1               Frequent
6                        1               Frequent
7                      180                 Rarely
8                       30                Monthly
9                       30                Monthly

In [16]:
df[['Discount_Applied','Promo_Code_Used']].head(10)

  Discount_Applied Promo_Code_Used
0              Yes             Yes
1              Yes             Yes
2               No             Yes
3               No              No
4              Yes             Yes
5              Yes              No
6              Yes             Yes
7              Yes             Yes
8               No             Yes
9               No             Yes

In [17]:
(df['Discount_Applied'] == df['Promo_Code_Used']).all()

np.False_

In [18]:
df.groupby(['Discount_Applied','Promo_Code_Used'])['Purchase_Amount'].mean()

Discount_Applied  Promo_Code_Used
No                No                 118.100000
                  Yes                149.906250
Yes               No                 160.454545
                  Yes                129.576923
Name: Purchase_Amount, dtype: float64

In [19]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in f:\users\dell\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in f:\users\dell\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in f:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in f:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [20]:
from sqlalchemy import create_engine

#step1 :connect to postgresql
#replace placeholders with your actual details
username = "postgres"
password = "123456"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")
#step 2:Load Dataframe into postgresql
table_name ="customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Database successfully loaded into table '{table_name}' in database '{database}'")

Database successfully loaded into table 'customer' in database 'customer_behavior'